### ISSUE TITLE
Get a list of satellite names

### ISSUE THREAD

**Issue by chriddyp** [pytroll/pyorbital#12]
Love this project!

I'm writing a UI around `pyorbital` and I'd like to supply a dropdown with a list of currently available satellites. Is there a list of the currently available satellites or a method to retrieve them? 

Thanks for the help!

**Comment by mraspaud** [comment]
@chriddyp thanks for your interest ! We're using TLE files from Celestrak.com, specifically the resources and weather files, so any platform from those files should work out of the box :)
