### ISSUE TITLE
Limitations on URLLIB Read for TLE

### ISSUE THREAD

**Issue by jordanlui** [pytroll/pyorbital#15]
Hi there,
Noticed that the tlefile.read will only check two NORAD TLE URLs from Celestrak. Was wondering if you could add the other Celestrak URLs, such as https://www.celestrak.com/NORAD/elements/cubesat.txt?

Thanks!

**Comment by mraspaud** [comment]
Hi,

Sure, that would be very nice ! I can't really work on this atm, but contributions are welcome :)

**Comment by jordanlui** [comment]
Hi Martin,
I made some small changes and submitted pull request.

Thanks!

Jordan Lui
Optical Engineering Research Associate, Roma Tre University
MASc Candidate, Simon Fraser University
BASc Chemical Engineering
University of Waterloo
http://ca.linkedin.com/in/jordanlui

**Comment by mraspaud** [comment]
Perfect ! Thanks !

**Comment by slawoszuznanski** [comment]
Dear all, would it be possible to manually read TLE from a text file? Celestrak URLs are very limiting...

**Comment by TAlonglong** [comment]
I use like this:

`TLES=/data/pytroll/tle-in/tle_db/tle-latest.txt <pytroll command which need tles>`

So `TLES` is a environmental variable.

**Comment by clausqr** [comment]
Hi! Would it be possible to add `'https://www.celestrak.com/NORAD/elements/engineering.txt'` to the list of TLEs?

i.e.:
``` diff
--- tlefile.py        2019-06-21 18:22:22.000000000 -0300
+++ tlefile.py        2019-06-21 18:22:42.000000000 -0300
@@ -40,8 +40,9 @@
             'http://celestrak.com/NORAD/elements/stations.txt',
             'https://www.celestrak.com/NORAD/elements/sarsat.txt',
             'https://www.celestrak.com/NORAD/elements/noaa.txt',
-            'https://www.celestrak.com/NORAD/elements/amateur.txt')
-
+            'https://www.celestrak.com/NORAD/elements/amateur.txt',
+            'https://www.celestrak.com/NORAD/elements/engineering.txt')
+            
 LOGGER = logging.getLogger(__name__)
 PKG_CONFIG_DIR = os.path.join(os.path.realpath(os.path.dirname(__file__)), 'etc')
```

**Comment by mraspaud** [comment]
I don't see why not, PR welcome !
