### ISSUE TITLE
SENTINEL-2 TLE files

### ISSUE THREAD

**Issue by anikfal** [pytroll/pyorbital#160]
Hi,
TLE information of Sentinel-1A, Sentinel-3A, Sentinel-3B, and Sentinel-5P are available by pyorbital. But why is Sentinel-2 missing? Can pyorbital be developed to include the TLEs of Sentinel-2?

The same issue can be seen for other platforms. For example, TLE information for the NOAA satellites 6 to 21 can be retrieved by pyorbital. But NOAA 13 is missing.

**Comment by simonrp84** [comment]
Hi @anikfal I have made a pull request (#161) that addresses this. It adds the missing sentinels plus some other satellites.
I didn't add NOAA-13 as it failed shortly after launch and never returned any data.
