### ISSUE TITLE
satellite.get_lonlatalt(now) returns wrong longitude with numpy < 1.11

### ISSUE THREAD

**Issue by joost823** [pytroll/pyorbital#27]
[numpy documentation regarding this behaviour](https://docs.scipy.org/doc/numpy-1.14.0/reference/arrays.datetime.html#changes-with-numpy-1-11)

if users with numpy < 1.11 are using the latest version of pyorbital, the timezone on their device will be used to calculate ```np.datetime64('2000-01-01T12:00'))``` in ```jdays2000()``` in ```astronomy.py```. In numpy => 1.11, the ```np.datetime64``` will always be in UTC by default. 

Suggestions:
check ```np.__version__``` in ```jdays2000()``` if you want to support older versions of numpy or change the requirements to np=>1.11

**Comment by mraspaud** [comment]
Thanks for spotting think. Do you feel like submitting a PR ?

**Comment by mraspaud** [comment]
This is now fixed in develop. Thanks for reporting the issue !
