### ISSUE TITLE
Unknown units in return value for get_alt_az

### ISSUE THREAD

**Issue by gerritholl** [pytroll/pyorbital#28]
#### Code Sample, a minimal, complete, and verifiable piece of code

```python
pyorbital.astronomy.get_alt_az(datetime.datetime.now(), atleast_1d(10), atleast_1d(0))
```
#### Problem description

It is unclear how to interpret the values -0.17 and -1.26.  It's either a correct value of unknown unit, or it's simply wrong.  Maybe it's both in radians?

#### Expected Output

I expect the documentation to describe the units of the angles.

#### Actual Result, Traceback if applicable

```python
(array([-0.17020899]), array([-1.25844873]))
```

#### Versions of Python, package at hand and relevant dependencies

pyorbital v1.3.1.

**Comment by mraspaud** [comment]
@gerritholl thanks for reporting this, you are absolutely right, this should be documented.
