### ISSUE TITLE
Operating System

### ISSUE THREAD

**Issue by TeCoEd** [pytroll/pyorbital#3]
Will this run on Raspian? @mraspaud 
Thanks

**Comment by mraspaud** [comment]
Never tried, but why not ? feel free to test and report back !

**Comment by TeCoEd** [comment]
will do, is it in the repository?
`sudo apt-get install pyorbital?`

**Comment by mraspaud** [comment]
no clue. I know some Ubuntu maintainer where packing some of the pytroll packages, don't know about pyorbital...

**Comment by TeCoEd** [comment]
OK, I will do some searching around.  
I am trying to use the Raspberry Pi to track the location of the ISS.

**Comment by TeCoEd** [comment]
All install in the Raspberry Pi - any hints how I track the ISS? Thanks

**Comment by adybbroe** [comment]
On 2015-05-26 22:19, Dan Aldred wrote:
> All install in the Raspberry Pi - any hints how I track the ISS? Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mraspaud/pyorbital/issues/3#issuecomment-105653510>.
>
Hi,

After downloading a tle file from Celestrak with TLE's for space stations:

from pyorbital.orbital import Orbital
iss = Orbital('ISS (ZARYA)', 
tle_file='/home/a000680/Downloads/stations.txt')

And this also (always) works, if you already know the TLEs:

iss = Orbital('ISS', line1="1 25544U 98067A   15146.56644382  .00005879 
  00000-0  92398-4 0  9999", line2="2 25544 051.6441 191.9827 0003959 
347.4661 112.0338 15.55193811944674")


But I couldn't get it to work just providing the name 'ISS (ZARYA)'. We 
have talked about allowing one to specify the NORAD catalog number as an 
alternative, which would be more robust compared to providing the 
correct name.

-Adam




-- 
Adam Dybbroe,
Satellite Remote Sensing Scientist,
Numerical models and Remote Sensing,
Core Services, Swedish Meteorological and Hydrological Institute (SMHI)
www.pytroll.org
nwcsaf.smhi.se
www.smhi.se

**Comment by TeCoEd** [comment]
Many thanks for your help, you are very kind, I am now trying to pull to longitude and latitude is there a simple code line for this?
Thanks
Dan

**Comment by mraspaud** [comment]
Please  have a look at the documentation here: http://pyorbital.readthedocs.org/en/latest/#computing-satellite-postion

**Comment by TeCoEd** [comment]
I have it working all now thank you for the links and tips, Dan
