### ISSUE TITLE
Issue(s) with get_next_passes

### ISSUE THREAD

**Issue by kevincroissant** [pytroll/pyorbital#36]
I have a script that uses pyorbital a lot, and very rarely an error appears when I run get_next_passes on 400+ satellites. The error is this:

```
/usr/local/lib/python3.5/dist-packages/pyorbital/orbital.py:370: RuntimeWarning: invalid value encountered in double_scalars
  ((b - a) * (f_b - f_c) - (b - c) * (f_b - f_a)))
```

Referencing this line: https://github.com/pytroll/pyorbital/blob/2bd8087cff802f040165c3483775359d8a61a896/pyorbital/orbital.py#L391

I also use get_next_passes to find the maximum elevation of an upcoming pass, my code for that looks like this. Also rarely, this elevation is completely wrong, but I've not noticed any correlation between that bug and the error I mentioned above.
```
            passes = calcPasses(calcTime, 24, observer, orb)
            nextPass = list(passes)
            maxElevationTime = nextPass[0][2]
            _, maxElevation = calcAzEl(maxElevationTime, observer, orb)
            print(idx+1, ' | ' + name + '  | Current elevation: ' + str(round(thisEl,2)) + ' [max: ' + str(round(maxElevation,2)) + ']')
```

Here is the implementation of calcPasses:
```
def calcPasses(calcTime, hours, observer, orb):
    passes = orb.get_next_passes(calcTime, hours, observer[0], observer[1], observer[2], tol=0.00001)
    return passes
```

I'm working on making a reproducible test, finding an exact TLE and pass that will cause the error, but this is all I have for now. I am not sure if these two bugs or related or not, but either way, it appears that get_next_passes can't be completely relied upon currently.

**Comment by mraspaud** [comment]
Thanks for reporting this. Could this be related to #34 and #35 ?

**Comment by kevincroissant** [comment]
Yes, was just looking at that, get_max_parab (where the error happens) indirectly relies upon the output of get_root_secant, so I am thinking maybe that pull request could fix all of the issues. I will try to test it out tomorrow.

**Comment by mraspaud** [comment]
That would be great! Thanks for the help

**Comment by mraspaud** [comment]
PR #35 is now merged, can we close this @kevincroissant ?

**Comment by kevincroissant** [comment]
All good now! Thanks Martin.
