### ISSUE TITLE
_read_tle fails to handle bstar values that start with + character

### ISSUE THREAD

**Issue by movermeyer** [pytroll/pyorbital#6]
_read_tle fails to handle bstar and mean_motion_sec_derivative values that start with + character.

Sometimes, these values starts with a '+'.

Example (from ISS):
1 25544U 98067A   15235.81765006 +.00009573 +00000-0 +14486-3 0  9999
2 25544 051.6452 106.3529 0001648 090.4174 004.9123 15.55401685958567

The + character is a valid character in this position, as indicated [by Celestrak](https://celestrak.com/columns/v04n03/:)
    
    "Columns with a '+' can have either a plus sign, a minus sign, or a space and columns with a '-' can have either a plus or minus sign (if the rest of the field is not blank)."

**Comment by mraspaud** [comment]
Thanks for reporting this, but as you mentioned in the other thread, it was fixed in the develop branch.
