### ISSUE TITLE
 can  this tool run 

### ISSUE THREAD

**Issue by lwk1542** [pytroll/pyorbital#62]
#### Code Sample, a minimal, complete, and verifiable piece of code

```python
# Your code here

```
#### Problem description

[this should also explain **why** the current behaviour is a problem and why the 
expected output is a better solution.]

#### Versions of Python, package at hand and relevant dependencies

Thank you for reporting an issue !

**Comment by mraspaud** [comment]
You'd have to be a bit more specific for us to help you. Please report the full problem according to the template.
