### ISSUE TITLE
ModuleNotFoundError: 'pyorbital' is not a package

### ISSUE THREAD

**Issue by mnaranjo** [pytroll/pyorbital#79]
Hi,
I have tried to perform the basic test described in the documentation after installing the package as indicated in the [link](https://pypi.org/project/pyorbital/) (I have also tried it with a coda environment and I get the same result), pyorbital version 1.6.1. 

```python
from pyorbital.orbital import Orbital
from datetime import datetime
# Use current TLEs from the internet:
orb = Orbital("Suomi NPP")
now = datetime.utcnow()
```

However, with the first import line I get the following error.

```shell
from pyorbital.orbital import Orbital
ModuleNotFoundError: No module named 'pyorbital.orbital'; 'pyorbital' is not a package
```

Am I missing something obvious?

Thank you very much

**Comment by djhoese** [comment]
Do you have a directory or file named pyorbital in your current directory? Otherwise, are you sure you are running with the same python environment rhat you installed pyorbital into?

**Comment by djhoese** [comment]
Any update on this @mnaranjo?

@joleenf you said you experienced something similar?

**Comment by joleenf** [comment]
Yes.  For me, ```pip install pyorbital``` solved the problem.
